# Configuration SecuOps pour SD Thai Food
app:
  name: sdthai
  type: fullstack
  version: 1.0.0
  description: SD Thai Food Platform - Complete restaurant management system (NestJS + Next.js)

# Configuration Git
git:
  repo: git@github.com:secuaas/sdthai.git
  branch: main

# Configuration de build
build:
  dockerfile: Dockerfile
  context: .
  registry: qq9o8vqe.c1.bhs5.container-registry.ovh.net
  namespace: secuops

# Configuration de déploiement
deploy:
  kubernetes:
    manifests: deploy/k8s/deployment.yaml
    namespace: sdthai

  dev:
    replicas: 1
    domain: sdthai-dev.secuaas.dev

  prod:
    replicas: 2
    domain: sdthai.ch

# Tests
tests:
  enabled: true
  backend:
    command: cd apps/api && pnpm test
    coverage: true
  frontend:
    command: cd apps/web && pnpm test
    coverage: true

# Audit et conformité
audit:
  enabled: true
  checks:
    - dockerfile-security
    - kubernetes-best-practices
    - dependencies-vulnerabilities
    - prisma-security
    - secrets-leak-prevention
    - code-quality

# Health checks
health:
  backend:
    endpoint: /api/health
    timeout: 5s
    interval: 10s
  frontend:
    endpoint: /
    timeout: 5s
    interval: 10s

# Secrets requis (créés manuellement dans K8s)
secrets:
  required:
    - DATABASE_URL
    - REDIS_URL
    - JWT_SECRET
    - JWT_REFRESH_SECRET
    - NEXT_PUBLIC_API_URL

# Hooks
hooks:
  pre-build:
    - echo "Starting SD Thai Food build..."
  post-build:
    - echo "Build completed for sdthai"
  pre-deploy:
    - kubectl get nodes
  post-deploy:
    - kubectl get all -n ${NAMESPACE}
