---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdthai
  namespace: sdthai
  labels:
    app.kubernetes.io/managed-by: secuops
    app.kubernetes.io/name: sdthai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdthai
  template:
    metadata:
      labels:
        app: sdthai
    spec:
      containers:
      - name: fullstack
        image: qq9o8vqe.c1.bhs5.container-registry.ovh.net/secuops/sdthai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: api
        - containerPort: 3001
          name: frontend
        envFrom:
        - secretRef:
            name: sdthai-secrets
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: sdthai-api
  namespace: sdthai
spec:
  selector:
    app: sdthai
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sdthai-frontend
  namespace: sdthai
spec:
  selector:
    app: sdthai
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdthai
  namespace: sdthai
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sdthai.secuaas.dev
    secretName: sdthai-secuaas-dev-tls
  rules:
  - host: sdthai.secuaas.dev
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: sdthai-api
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdthai-frontend
            port:
              number: 80
